global using System.Collections;
global using System.Collections.Specialized;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Reactive.Linq;
global using System.Reflection;
global using Newtonsoft.Json;
global using Utility.Changes;
global using Utility.Commands;
global using Utility.Helpers;
global using Utility.Helpers.Reflection;
global using Utility.Interfaces.NonGeneric;
global using Descriptor = System.ComponentModel.PropertyDescriptor;
global using Type = System.Type;